<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_VXXSkRirEem2CYYVeB7Aag" nsURI="http://de.hub.el/EL/1.0" nsPrefix="el">
  <eClassifiers xsi:type="ecore:EClass" name="ELPackage" eSuperTypes="././fixed/a10.ecore#//ELNamedElement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VXYgsBirEem2CYYVeB7Aag" value="_VXYgsRirEem2CYYVeB7Aag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELClass" eSuperTypes="././fixed/a10.ecore#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELVariable" eSuperTypes="././fixed/a10.ecore#//ELTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELMethod" eSuperTypes="././fixed/a10.ecore#//ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass ././fixed/a10.ecore#//ELBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELField" eSuperTypes="././fixed/a10.ecore#//ELVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELExpression" eSuperTypes="././fixed/a10.ecore#//ELStatement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VXZu0BirEem2CYYVeB7Aag" value="_VXZu0RirEem2CYYVeB7Aag"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELLiteral" eSuperTypes="././fixed/a10.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELCall" eSuperTypes="././fixed/a10.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisArgument" eType="ecore:EClass ././fixed/a10.ecore#//ELExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAccess" eSuperTypes="././fixed/a10.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ././fixed/a10.ecore#//ELVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStatement" eSuperTypes="././fixed/a10.ecore#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="ecore:EClass ././fixed/a10.ecore#//ELBlockStarementKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOp">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VXa89BirEem2CYYVeB7Aag" value="_VXa89RirEem2CYYVeB7Aag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELDataType" eSuperTypes="././fixed/a10.ecore#//ELClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELTypedElement" eSuperTypes="././fixed/a10.ecore#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ././fixed/a10.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStarementKind">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VXa88BirEem2CYYVeB7Aag" value="_VXa88RirEem2CYYVeB7Aag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELModel" eSuperTypes="././fixed/a10.ecore#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="ecore:EClass ././fixed/a10.ecore#//ELOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="ecore:EClass ././fixed/a10.ecore#//ELBlockStarementKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ELOpKind">
    <eLiterals name="infix" literal="_VXXSkBirEem2CYYVeB7Aag"/>
    <eLiterals name="suffix"/>
    <eLiterals name="prefix"/>
    <eLiterals name="syntax" literal="syntax"/>
    <eLiterals name="placeholder5365221" literal="_VXVdYRirEem2CYYVeB7Aag">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_VXa88hirEem2CYYVeB7Aag" value="_VXa88xirEem2CYYVeB7Aag"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="placeholder8419521" eSuperTypes="././fixed/a10.ecore#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ././fixed/a10.ecore#//ELExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="ecore:EClass ././fixed/a10.ecore#//ELVariable"/>
  </eClassifiers>
</ecore:EPackage>
