<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="el" nsURI="http://de.hub.el/EL/1.0" nsPrefix="el">
  <eClassifiers xsi:type="ecore:EClass" name="ELPackage" eSuperTypes="././fixed/a11.ecore#//_VXmjIBirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELClass" eSuperTypes="././fixed/a11.ecore#//_VXmjIBirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELMethod" containment="true">
      <eAnnotations source="_VXqNgBirEem2CYYVeB7Aag"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELVariable" eSuperTypes="././fixed/a11.ecore#//ELTypedElement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VXnKMBirEem2CYYVeB7Aag" value="_VXnKMRirEem2CYYVeB7Aag"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELMethod" eSuperTypes="././fixed/a11.ecore#//ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELField" eSuperTypes="././fixed/a11.ecore#//ELVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELExpression" eSuperTypes="././fixed/a11.ecore#//ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELLiteral" eSuperTypes="././fixed/a11.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOpCall" eSuperTypes="././fixed/a11.ecore#//ELCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELCall" eSuperTypes="././fixed/a11.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" eType="ecore:EClass ././fixed/a11.ecore#//ELMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_VXo_YBirEem2CYYVeB7Aag"
        eType="ecore:EClass ././fixed/a11.ecore#//ELExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAccess" eSuperTypes="././fixed/a11.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ././fixed/a11.ecore#//ELVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStatement" eSuperTypes="././fixed/a11.ecore#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="ecore:EClass ././fixed/a11.ecore#//_VXt34BirEem2CYYVeB7Aag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EEnum ././fixed/a11.ecore#//ELOpKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELDataType" eSuperTypes="././fixed/a11.ecore#//ELClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="_VXmjIBirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELTypedElement" eSuperTypes="././fixed/a11.ecore#//_VXmjIBirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ././fixed/a11.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_VXt34BirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELModel" eSuperTypes="././fixed/a11.ecore#//_VXmjIBirEem2CYYVeB7Aag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//ELPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="ecore:EClass ././fixed/a11.ecore#//ELOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="ecore:EClass ././fixed/a11.ecore#//_VXt34BirEem2CYYVeB7Aag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ELOpKind">
    <eLiterals name="infix" literal="infix"/>
    <eLiterals name="_VXtQ0BirEem2CYYVeB7Aag"/>
    <eLiterals name="prefix"/>
    <eLiterals name="syntax" literal="syntax"/>
    <eLiterals name="placeholder1038671" literal="_VXpmcBirEem2CYYVeB7Aag"/>
  </eClassifiers>
</ecore:EPackage>
