<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_VX6sMhirEem2CYYVeB7Aag" nsURI="http://de.hub.el/EL/1.0" nsPrefix="el">
  <eAnnotations source="http://www.modelversioning.org/ecoremutator">
    <details key="_VX8hYhirEem2CYYVeB7Aag" value="_VX8hYxirEem2CYYVeB7Aag"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ELPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELField" containment="true">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_VX7TQBirEem2CYYVeB7Aag" value="_VX7TQRirEem2CYYVeB7Aag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClases" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELMethod" eSuperTypes="././fixed/a12.ecore#//ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass" containment="true">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_VX9IcBirEem2CYYVeB7Aag" value="_VX9IcRirEem2CYYVeB7Aag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass ././fixed/a12.ecore#//ELBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELField"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELExpression" eSuperTypes="././fixed/a12.ecore#//ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELLiteral" eSuperTypes="././fixed/a12.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="placeholder1333781" eSuperTypes="././fixed/a12.ecore#//ELCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="ecore:EClass ././fixed/a12.ecore#//ELOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELCall" eSuperTypes="././fixed/a12.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" eType="ecore:EClass ././fixed/a12.ecore#//ELMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisArgument" eType="ecore:EClass ././fixed/a12.ecore#//ELExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAccess" eSuperTypes="././fixed/a12.ecore#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStatement" eSuperTypes="././fixed/a12.ecore#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELExpression" containment="true">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_VX6sMBirEem2CYYVeB7Aag" value="_VX6sMRirEem2CYYVeB7Aag"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EEnum ././fixed/a12.ecore#//ELOpKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operands" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_VX8hYBirEem2CYYVeB7Aag" value="_VX8hYRirEem2CYYVeB7Aag"/>
        <details key="_VX9vgBirEem2CYYVeB7Aag" value="_VX9vgRirEem2CYYVeB7Aag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_VX9IchirEem2CYYVeB7Aag"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELDataType" eSuperTypes="././fixed/a12.ecore#//ELClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ././fixed/a12.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStarementKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" eType="ecore:EClass ././fixed/a12.ecore#//ELOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="ecore:EClass ././fixed/a12.ecore#//ELBlockStarementKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ELOpKind">
    <eLiterals name="infix" literal="infix"/>
    <eLiterals name="suffix"/>
    <eLiterals name="prefix"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAssignment" eSuperTypes="././fixed/a12.ecore#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
</ecore:EPackage>
