<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="el" nsURI="http://de.hub.el/EL/1.0" nsPrefix="el">
  <eClassifiers xsi:type="ecore:EClass" name="ELPackage" eSuperTypes="#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELClass" eSuperTypes="#//ELNamedElement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dXywQiknEemoEoNTCLil9Q" value="_dXywQyknEemoEoNTCLil9Q"/>
      </eAnnotations>
      <details key="_dXvF4iknEemoEoNTCLil9Q" value="_dXvF4yknEemoEoNTCLil9Q"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//ELMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//ELField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClases" upperBound="-1"
        eType="#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELVariable" eSuperTypes="#//ELTypedElement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dX0lciknEemoEoNTCLil9Q" value="_dX0lcyknEemoEoNTCLil9Q"/>
      </eAnnotations>
      <details key="_dXrbgCknEemoEoNTCLil9Q" value="_dXrbgSknEemoEoNTCLil9Q"/>
      <details key="_dXywQCknEemoEoNTCLil9Q" value="_dXywQSknEemoEoNTCLil9Q"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELMethod" eSuperTypes="#//ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ELVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="#//ELVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//ELBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELField" eSuperTypes="#//ELVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELStatement">
    <eOperations name="_dXw7ECknEemoEoNTCLil9Q" ordered="false" unique="false" lowerBound="97"
        upperBound="25"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//ELStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELExpression" eSuperTypes="#//ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELLiteral" eSuperTypes="#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOpCall" eSuperTypes="#//ELCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="#//ELOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELCall" eSuperTypes="#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//ELExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" eType="#//ELMethod">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dXsCkCknEemoEoNTCLil9Q" value="_dXsCkSknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisArgument" eType="#//ELExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAccess" eSuperTypes="#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//ELVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStatement" eSuperTypes="#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="#//ELBlock" containment="true">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <eAnnotations source="_dXzXUCknEemoEoNTCLil9Q"/>
        <details key="_dXqNYCknEemoEoNTCLil9Q" value="_dXqNYSknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="#//ELBlockStarementKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//ELExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ELOpKind">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dXqNYiknEemoEoNTCLil9Q" value="_dXqNYyknEemoEoNTCLil9Q"/>
        <contents/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operands" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="_dXt3wCknEemoEoNTCLil9Q">
        <eAnnotations source="http://www.modelversioning.org/ecoremutator">
          <details key="_dXvF4CknEemoEoNTCLil9Q" value="_dXvF4SknEemoEoNTCLil9Q"/>
        </eAnnotations>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELDataType" eSuperTypes="#//ELClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dXtQsiknEemoEoNTCLil9Q" value="_dXtQsyknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELTypedElement" eSuperTypes="#//ELNamedElement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_dXspoCknEemoEoNTCLil9Q" value="_dXspoSknEemoEoNTCLil9Q"/>
      <details key="_dXvs8CknEemoEoNTCLil9Q" value="_dXvs8SknEemoEoNTCLil9Q"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ELClass">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dXwUACknEemoEoNTCLil9Q" value="_dXwUASknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStarementKind">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_dXyJMCknEemoEoNTCLil9Q" value="_dXyJMSknEemoEoNTCLil9Q"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELModel" eSuperTypes="#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//ELPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="#//ELOp"
        containment="true">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <eAnnotations source="http://www.modelversioning.org/ecoremutator">
          <details key="_dXtQsCknEemoEoNTCLil9Q" value="_dXtQsSknEemoEoNTCLil9Q"/>
        </eAnnotations>
        <details key="_dXq0cCknEemoEoNTCLil9Q" value="_dXq0cSknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//ELBlockStarementKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ELOpKind">
    <eLiterals name="infix" literal="infix"/>
    <eLiterals name="suffix">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_dX0lcCknEemoEoNTCLil9Q" value="_dX0lcSknEemoEoNTCLil9Q"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="prefix"/>
    <eLiterals name="syntax" literal="syntax"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAssignment" eSuperTypes="#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//ELExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="#//ELVariable"/>
  </eClassifiers>
</ecore:EPackage>
