<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="el" nsURI="http://de.hub.el/EL/1.0" nsPrefix="_VViGkBirEem2CYYVeB7Aag">
  <eClassifiers xsi:type="ecore:EClass" name="ELClass" eSuperTypes="#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//ELMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//ELField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClases" upperBound="-1"
        eType="#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="#//ELClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_VVlw8BirEem2CYYVeB7Aag" eSuperTypes="#//ELTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELMethod" eSuperTypes="#//ELTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//_VVlw8BirEem2CYYVeB7Aag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVariables" upperBound="-1"
        eType="#//_VVlw8BirEem2CYYVeB7Aag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//ELBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELField" eSuperTypes="#//_VVlw8BirEem2CYYVeB7Aag"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlock"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELExpression" abstract="true" eSuperTypes="#//ELStatement">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VVjUsBirEem2CYYVeB7Aag" value="_VVjUsRirEem2CYYVeB7Aag"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELLiteral" eSuperTypes="#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOpCall" eSuperTypes="#//ELCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="#//ELOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELCall" eSuperTypes="#//ELExpression">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VVhfgxirEem2CYYVeB7Aag" value="_VVhfhBirEem2CYYVeB7Aag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//ELExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" eType="#//ELMethod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisArgument" eType="#//ELExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_VVb_8BirEem2CYYVeB7Aag" eSuperTypes="#//ELExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//_VVlw8BirEem2CYYVeB7Aag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStatement" eSuperTypes="#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="#//ELBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_VVlJ4BirEem2CYYVeB7Aag"
        eType="#//ELBlockStarementKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//ELExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//_VVj7wBirEem2CYYVeB7Aag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operands" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedence" lowerBound="98"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELDataType" eSuperTypes="#//ELClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELTypedElement" eSuperTypes="#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELBlockStarementKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELModel" eSuperTypes="#//ELNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="#//ELOp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="_VVj7wBirEem2CYYVeB7Aag">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_VVbY4BirEem2CYYVeB7Aag" value="_VVbY4RirEem2CYYVeB7Aag"/>
      <details key="_VVbY4hirEem2CYYVeB7Aag" value="_VVbY4xirEem2CYYVeB7Aag"/>
    </eAnnotations>
    <eLiterals name="infix" literal="infix"/>
    <eLiterals name="suffix"/>
    <eLiterals name="prefix"/>
    <eLiterals name="syntax" literal="_VVg4cBirEem2CYYVeB7Aag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELAssignment" eSuperTypes="#//ELStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//ELExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="#//_VVlw8BirEem2CYYVeB7Aag"/>
  </eClassifiers>
  <eSubpackages name="_VVhfgBirEem2CYYVeB7Aag" nsURI="_VVhfgRirEem2CYYVeB7Aag" nsPrefix="_VVhfghirEem2CYYVeB7Aag"/>
</ecore:EPackage>
