<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel" nsURI="http://hu-berlin.de/sam/emfhbase/testmodel"
    nsPrefix="tm">
  <eClassifiers xsi:type="ecore:EClass" name="TestObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentedContents" upperBound="-1"
        eType="#//TestObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_mK7lkClCEemYDvBcHp3few">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_mK-B0ClCEemYDvBcHp3few" value="_mK-B0SlCEemYDvBcHp3few"/>
    </eAnnotations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../../../de.hub.emffrag/metamodels/emffrag.ecore#//IndexedMap">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eTypeArguments eClassifier="#//TestObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum">
    <eLiterals name="literal1"/>
    <eLiterals name="literal2"/>
    <eLiterals literal="_mK-o4SlCEemYDvBcHp3few">
      <eAnnotations source="_mK_P8ClCEemYDvBcHp3few"/>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="_mK_P8SlCEemYDvBcHp3few" eSuperTypes="#//TestObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedReferences" unique="false"
        upperBound="-1" eType="#//TestObject">
      <eAnnotations source="de.hub.emffrag">
        <details key="indexes" value="true"/>
        <contents/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
