<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel" nsURI="http://hu-berlin.de/sam/emfhbase/testmodel"
    nsPrefix="tm">
  <eClassifiers xsi:type="ecore:EClass" name="TestObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularContents" upperBound="-1"
        eType="#//TestObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentedContents" upperBound="-1"
        eType="#//TestObject" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="fragments" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_tuoDsClGEemj3ZP_e3zW7A" value="_tuoDsSlGEemj3ZP_e3zW7A"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" unique="false" upperBound="-1"
        eType="#//TestObject">
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_tuhWAClGEemj3ZP_e3zW7A" value="_tuhWASlGEemj3ZP_e3zW7A"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestObjectIndex">
    <eAnnotations>
      <details key="_tuncoClGEemj3ZP_e3zW7A" value="_tuncoSlGEemj3ZP_e3zW7A"/>
    </eAnnotations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../../../de.hub.emffrag/metamodels/emffrag.ecore#//IndexedMap">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eTypeArguments eClassifier="#//TestObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum">
    <eLiterals name="literal1">
      <eAnnotations source="_tuncoilGEemj3ZP_e3zW7A">
        <details key="_tulAYClGEemj3ZP_e3zW7A" value="_tulAYSlGEemj3ZP_e3zW7A"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="literal2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestObjectWithIndexes" eSuperTypes="#//TestObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedReferences" unique="false"
        upperBound="-1" eType="#//TestObject">
      <eAnnotations source="de.hub.emffrag">
        <details key="indexes" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedContents" upperBound="-1"
        eType="#//TestObject" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="indexes" value="true"/>
        <contents/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
