<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel" nsURI="http://hu-berlin.de/sam/emfhbase/testmodel"
    nsPrefix="tm">
  <eClassifiers xsi:type="ecore:EClass" name="TestObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularContents" upperBound="-1"
        eType="#//TestObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentedContents" upperBound="-1"
        eType="#//TestObject" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <eAnnotations source="_ttzkUClGEemj3ZP_e3zW7A">
          <details key="_ttnXEilGEemj3ZP_e3zW7A" value="_ttnXEylGEemj3ZP_e3zW7A"/>
        </eAnnotations>
        <details key="fragments" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_tty9QClGEemj3ZP_e3zW7A" value="_tty9QSlGEemj3ZP_e3zW7A"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestObjectIndex">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../../../de.hub.emffrag/metamodels/emffrag.ecore#//IndexedMap">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eTypeArguments eClassifier="#//TestObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum">
    <eLiterals name="literal1"/>
    <eLiterals name="literal2" value="99" literal="_ttwhAClGEemj3ZP_e3zW7A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestObjectWithIndexes" eSuperTypes="#//TestObject">
    <eAnnotations source="http://www.modelversioning.org/ecoremutator">
      <details key="_ttv58ClGEemj3ZP_e3zW7A" value="_ttv58SlGEemj3ZP_e3zW7A"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedReferences" unique="false"
        upperBound="-1" eType="#//TestObject">
      <eAnnotations source="de.hub.emffrag">
        <details key="indexes" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedContents" upperBound="-1"
        eType="#//TestObject" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="indexes" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelversioning.org/ecoremutator">
        <details key="_tty9QilGEemj3ZP_e3zW7A" value="_tty9QylGEemj3ZP_e3zW7A"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
